### ISSUE TITLE
Hello!!

### ISSUE THREAD

**Issue by Error62AjBlKOp8061** [pumpkinhasapatch/dokodemo-psp-english#2]
I see you worked on this project 9 hours ago. I recently found about this cute game and my parents have a PSP. So, here are some questions:

1. Will it work if it's downloaded from a rom website?
2. Do I need to install it using the CMD file?

I hope you're doing well!

**Comment by pumpkinhasapatch** [comment]
I have updated the project README with better instructions and information, which you can [read about here](https://github.com/pumpkinhasapatch/dokodemo-psp-english#installation). The game translation should work with most copies of Doko Demo Issyo for PSP (even a real disc), and you can use a program called [xdelta UI](https://www.romhacking.net/utilities/598/) for easy installation.

The command files are mainly for making changes to the code and building a new version of the translation. If you just want to play the game in English, you should get the xdelta patch from our [Releases page](https://github.com/pumpkinhasapatch/dokodemo-psp-english/releases) and try using the [xdelta UI patcher](https://github.com/pumpkinhasapatch/dokodemo-psp-english#applying-xdelta-patches) which is easier and works most of the time.

I can't endorse doing what you mentioned in "1", but since the original game never got released outside of Japan the only way to get it legitimately is from a few second-hand copies from online sellers like eBay/Buyee. There is no way to buy it brand new anymore even in Japan since the [PSP store shut down](https://comicbook.com/gaming/news/psp-store-shuts-down/), so it's basically [abandonware](https://en.wikipedia.org/wiki/Abandonware) and you will have to make your own decisions on how to obtain it.

The translation project does not have much done yet, only some menus and Toro's text at the start of the game are in English even with this patch. I am working on adding more English content soon, but don't expect to play much of the game yet since most things still use the original Japanese text. I should upload some screenshots of the translated game to show what's been done.

**Comment by Error62AjBlKOp8061** [comment]
Thanks! I'll try out later!
